apiVersion: v1
kind: Secret
metadata:
  name: mysecrets
  namespace: petclinic
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3N3b3Jk  # rootpassword
  mysql-username: Y2F0LXVzZXI=           # cat-user
  mysql-password: cGFzc3dvcmQxIQ==       # cat-password1!
  mysql-database:  cGV0Y2xpbmljLWRi      # petclinic-db
